import { Link, useLocation } from 'wouter';
import { useLocale, formatDate } from '@/lib/locale';
import { State, InlineError } from '@/components/clinic-ui';
import type { ReactNode, FormEvent } from 'react';

export function FinanceTabs(){const [path]=useLocation();const {t}=useLocale();return <nav className="ledger-tabs" aria-label={t('finance')}>{([['/finance','invoices'],['/finance/expenses','expenses'],['/finance/suppliers','suppliers'],['/finance/reports','reports']] as const).map(([href,key])=><Link key={href} href={href} className={(href==='/finance'?path==='/finance'||path.startsWith('/finance/invoices'):path.startsWith(href))?'active':''} data-testid={`link-finance-${key}`}>{t(key)}</Link>)}</nav>}
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="field">{label}{children}</label>}
export function Input({value,onChange,type='text',required=false,min,step,placeholder,testId}:{value:string;onChange:(v:string)=>void;type?:string;required?:boolean;min?:string;step?:string;placeholder?:string;testId:string}){return <input className="input" value={value} onChange={e=>onChange(e.target.value)} type={type} required={required} min={min} step={step} placeholder={placeholder} data-testid={testId}/>}
export function Modal({title,onClose,onSubmit,pending,error,children}:{title:string;onClose:()=>void;onSubmit:(e:FormEvent)=>void;pending:boolean;error?:string;children:ReactNode}){const {t}=useLocale();return <div className="ledger-modal" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="ledger-dialog" role="dialog" aria-modal="true" aria-label={title}><div style={{display:'flex',justifyContent:'space-between',alignItems:'start',gap:12}}><div className="eyebrow">DentOzone / {t('workspace')}</div><button type="button" className="btn btn-outline" onClick={onClose} aria-label={t('cancel')} data-testid="button-close-dialog">×</button></div><h2 className="display">{title}</h2><form onSubmit={onSubmit} className="ledger-form">{children}{error&&<InlineError message={error}/>}<div className="ledger-actions"><button type="button" className="btn btn-outline" onClick={onClose} data-testid="button-cancel-dialog">{t('cancel')}</button><button type="submit" className="btn btn-primary" disabled={pending} data-testid="button-save-dialog">{pending?t('saving'):t('save')}</button></div></form></div></div>}
export function QueryState({loading,error,empty,retry}:{loading:boolean;error:boolean;empty:boolean;retry:()=>void}){const {t}=useLocale();return loading?<State kind="loading"/>:error?<State kind="error" onRetry={retry}/>:empty?<State kind="empty" title={t('noRecords')} description={t('noRecordsSub')}/>:null}
export function DateText({value}:{value:string}){const {language}=useLocale();return <time dateTime={value}>{formatDate(value,language)}</time>}
export function Pair({label,value}:{label:ReactNode;value:ReactNode}){return <div className="ledger-pair"><span>{label}</span><strong>{value}</strong></div>}