import { getGetDashboardQueryKey, getListAppointmentsQueryKey, getGetAppointmentQueryKey, getListPatientVisitsQueryKey, getGetVisitQueryKey, getListPatientOdontogramQueryKey, getListPatientTreatmentPlansQueryKey, getGetTreatmentPlanQueryKey } from '@workspace/api-client-react';
import type { QueryClient } from '@tanstack/react-query';

export const tr=(ar:boolean,en:string,arabic:string)=>ar?arabic:en;
export const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const arabicLabels:Record<string,string>={scheduled:'مجدول',confirmed:'مؤكد',arrived:'حضر',completed:'مكتمل',no_show:'لم يحضر',cancelled:'ملغى',draft:'مسودة',active:'نشط',pending:'قيد الانتظار',in_progress:'جارٍ التنفيذ',healthy:'سليم',caries:'تسوس',filled:'محشو',crown:'تاج',missing:'مفقود',root_canal:'علاج الجذور',implant:'زراعة',extraction_needed:'يحتاج للخلع',unerupted:'لم يبزغ',other:'أخرى'};
export const careLabel=(value:string,ar:boolean)=>ar?(arabicLabels[value]||label(value)):label(value);
export const cairoDay=(date:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
export const cairoDateTime=(date:string)=>{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(date));const p=(key:string)=>parts.find(x=>x.type===key)?.value||'';return `${p('year')}-${p('month')}-${p('day')}T${p('hour')}:${p('minute')}`};
export function cairoISO(value:string){if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(value))throw Error('Invalid date and time');const target=Date.parse(value+'Z');if(!Number.isFinite(target))throw Error('Invalid date and time');const parts=(time:number)=>{const s=cairoDateTime(new Date(time).toISOString());return Date.parse(s+'Z')};let guess=target-7200000;for(let i=0;i<4;i++)guess+=target-parts(guess);if(parts(guess)!==target)throw Error('This local time does not exist in Cairo. Choose another time.');return new Date(guess).toISOString()}
export const dateText=(iso:string,ar:boolean,opts?:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat(ar?'ar-EG':'en-GB',{timeZone:'Africa/Cairo',day:'numeric',month:'short',year:'numeric',...opts}).format(new Date(iso));
export function invalidateCare(qc:QueryClient,patientId?:number,appointmentId?:number,visitId?:number,planId?:number){void qc.invalidateQueries({queryKey:getListAppointmentsQueryKey().slice(0,1)});void qc.invalidateQueries({queryKey:getGetDashboardQueryKey()});if(appointmentId)void qc.invalidateQueries({queryKey:getGetAppointmentQueryKey(appointmentId)});if(patientId){void qc.invalidateQueries({queryKey:getListPatientVisitsQueryKey(patientId)});void qc.invalidateQueries({queryKey:getListPatientOdontogramQueryKey(patientId)});void qc.invalidateQueries({queryKey:getListPatientTreatmentPlansQueryKey(patientId)})}if(visitId)void qc.invalidateQueries({queryKey:getGetVisitQueryKey(visitId)});if(planId)void qc.invalidateQueries({queryKey:getGetTreatmentPlanQueryKey(planId)})}
export const errorText=(e:unknown,ar:boolean,context?:'appointment')=>{const x=e as {status?:number;response?:{status?:number};message?:string};return (x?.status===409||x?.response?.status===409||x?.message?.includes('409'))?(context==='appointment'?tr(ar,'This time conflicts with another appointment. Choose a different time, doctor, or chair.','هذا الوقت يتعارض مع موعد آخر. اختر وقتًا أو طبيبًا أو كرسيًا مختلفًا.'):tr(ar,'This action conflicts with the current record. Refresh the page and check its latest status before trying again.','يتعارض هذا الإجراء مع حالة السجل الحالية. حدّث الصفحة وتحقق من آخر حالة قبل المحاولة مجددًا.')):x?.message||tr(ar,'Could not save. Please try again.','تعذر الحفظ. حاول مرة أخرى.')};