import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useListAppointments, useCreateAppointment, useUpdateAppointment, useCancelAppointment, useListAppointmentDoctors, useGetPatients, useGetAppointment, useCreatePatientVisit, useListPatientVisits, getGetAppointmentQueryKey, getListPatientVisitsQueryKey, type Appointment, type StaffSession } from '@workspace/api-client-react';
import { Link, useLocation, useParams } from 'wouter';
import { CalendarDays, ChevronLeft, ChevronRight, Plus, X } from 'lucide-react';
import { BackLink, InlineError, PageHeading, State } from '@/components/clinic-ui';
import { useLocale } from '@/lib/locale';
import { cairoDay, cairoDateTime, cairoISO, careLabel, dateText, errorText, invalidateCare, label, tr } from '@/lib/care';

const shift=(d:string,n:number)=>{const x=new Date(`${d}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const range=(day:string,view:string)=>{const d=new Date(`${day}T12:00:00Z`);if(view==='week'){const from=shift(day,-((d.getUTCDay()+6)%7));return {from,to:shift(from,7)}}if(view==='month'){const from=day.slice(0,7)+'-01';const next=new Date(`${from}T12:00:00Z`);next.setUTCMonth(next.getUTCMonth()+1);return {from,to:next.toISOString().slice(0,10)}}return {from:day,to:shift(day,1)}};
const fullRange=(r:{from:string;to:string})=>({from:cairoISO(`${r.from}T00:00`),to:cairoISO(`${r.to}T00:00`)});
const canWrite=(role:string)=>['owner','manager','reception','dentist'].includes(role);
const canClinical=(role:string)=>['owner','manager','dentist','assistant'].includes(role);

export function AppointmentForm({session,appointment,onClose,onSaved,initialDay}: {session:StaffSession;appointment?:Appointment;onClose:()=>void;onSaved:(id:number)=>void;initialDay?:string}){
 const {language}=useLocale(),ar=language==='ar',qc=useQueryClient();const doctors=useListAppointmentDoctors();const [search,setSearch]=useState('');const patients=useGetPatients({search,limit:50});const create=useCreateAppointment(),update=useUpdateAppointment();const [patientId,setPatientId]=useState(appointment?.patientId||0),[doctorId,setDoctorId]=useState(appointment?.doctorStaffId||0),[start,setStart]=useState(appointment?cairoDateTime(appointment.startsAt):`${initialDay||cairoDay(new Date())}T09:00`),[end,setEnd]=useState(appointment?cairoDateTime(appointment.endsAt):`${initialDay||cairoDay(new Date())}T09:30`),[treatment,setTreatment]=useState(appointment?.treatment||''),[chair,setChair]=useState(appointment?.chair||''),[notes,setNotes]=useState(appointment?.notes||''),[status,setStatus]=useState<'scheduled'|'confirmed'|'arrived'|'completed'|'no_show'>(appointment?.status==='cancelled'?'scheduled':appointment?.status||'scheduled'),[error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const startsAt=cairoISO(start),endsAt=cairoISO(end);if(new Date(endsAt)<=new Date(startsAt))throw Error(tr(ar,'End time must be after start time.','يجب أن يكون وقت النهاية بعد البداية.'));if(!doctorId)throw Error(tr(ar,'Select a doctor.','اختر طبيبًا.'));if(!appointment&&!patientId)throw Error(tr(ar,'Select an active patient.','اختر مريضًا نشطًا.'));const data={doctorStaffId:doctorId,startsAt,endsAt,treatment:treatment.trim(),chair:chair.trim(),notes:notes.trim()};const saved=appointment?await update.mutateAsync({appointmentId:appointment.id,data:{...data,status}}):await create.mutateAsync({data:{...data,patientId}});invalidateCare(qc,saved.patientId,saved.id);onSaved(saved.id)}catch(e){setError(errorText(e,ar,'appointment'))}};
 return <div className="care-dialog" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="care-panel" role="dialog" aria-modal="true" aria-label={tr(ar,appointment?'Edit appointment':'New appointment',appointment?'تعديل الموعد':'موعد جديد')}><div className="care-toolbar"><div><div className="care-kicker">{tr(ar,'SCHEDULE','الجدول')}</div><h2 className="care-title" style={{margin:0}}>{tr(ar,appointment?'Edit appointment':'New appointment',appointment?'تعديل الموعد':'موعد جديد')}</h2></div><button className="btn btn-outline" onClick={onClose} data-testid="button-close-appointment"><X size={16}/></button></div><form onSubmit={submit} className="care-form">
 {!appointment&&<div className="care-field care-span"><label htmlFor="patient-search">{tr(ar,'Find a patient','ابحث عن مريض')}</label><input id="patient-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={tr(ar,'Name, code or phone','الاسم أو الكود أو الهاتف')} data-testid="input-appointment-patient-search"/><select required value={patientId||''} onChange={e=>setPatientId(Number(e.target.value))} data-testid="select-appointment-patient"><option value="">{patients.isLoading?tr(ar,'Searching…','جارٍ البحث…'):tr(ar,'Select active patient','اختر مريضًا نشطًا')}</option>{patients.data?.filter(p=>p.status==='active').map(p=><option value={p.id} key={p.id}>{p.fullName} · {p.patientCode}</option>)}</select>{patients.isError&&<InlineError message={tr(ar,'Patient search unavailable.','تعذر البحث عن المرضى.')}/>}</div>}
 <label className="care-field">{tr(ar,'Doctor','الطبيب')}<select required value={doctorId||''} onChange={e=>setDoctorId(Number(e.target.value))} data-testid="select-appointment-doctor"><option value="">{tr(ar,'Select doctor','اختر طبيبًا')}</option>{doctors.data?.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="care-field">{tr(ar,'Chair','الكرسي')}<input value={chair} onChange={e=>setChair(e.target.value)} data-testid="input-appointment-chair"/></label>
 <label className="care-field">{tr(ar,'Starts · Cairo time','البداية · توقيت القاهرة')}<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)} data-testid="input-appointment-start"/></label><label className="care-field">{tr(ar,'Ends · Cairo time','النهاية · توقيت القاهرة')}<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)} data-testid="input-appointment-end"/></label>
 <label className="care-field care-span">{tr(ar,'Treatment','العلاج')}<input required maxLength={180} value={treatment} onChange={e=>setTreatment(e.target.value)} data-testid="input-appointment-treatment"/></label>{appointment&&<label className="care-field care-span">{tr(ar,'Status','الحالة')}<select value={status} onChange={e=>setStatus(e.target.value as typeof status)} data-testid="select-appointment-status">{(['scheduled','confirmed','arrived','completed','no_show'] as const).map(s=><option value={s} key={s}>{careLabel(s,ar)}</option>)}</select></label>}<label className="care-field care-span">{tr(ar,'Notes','ملاحظات')}<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} data-testid="input-appointment-notes"/></label>
 {error&&<div className="care-span"><InlineError message={error}/></div>}<div className="care-actions care-span"><button className="btn btn-primary" disabled={create.isPending||update.isPending||doctors.isLoading} data-testid="button-save-appointment">{create.isPending||update.isPending?tr(ar,'Saving…','جارٍ الحفظ…'):tr(ar,'Save appointment','حفظ الموعد')}</button><button type="button" className="btn btn-outline" onClick={onClose} data-testid="button-dismiss-appointment">{tr(ar,'Cancel','إلغاء')}</button></div></form></div></div>
}

export default function Appointments({session}:{session:StaffSession}){const {language}=useLocale(),ar=language==='ar';const [,navigate]=useLocation();const [day,setDay]=useState(cairoDay(new Date())),[view,setView]=useState<'day'|'week'|'month'>('day'),[editing,setEditing]=useState(false);const r=range(day,view),q=useListAppointments(fullRange(r));const days=Array.from({length:Math.round((Date.parse(r.to)-Date.parse(r.from))/86400000)},(_,i)=>shift(r.from,i));const calendarDays=view==='month'?Array.from({length:Math.ceil((days.length+(new Date(`${r.from}T12:00Z`).getUTCDay()+6)%7)/7)*7},(_,i)=>shift(r.from,i-((new Date(`${r.from}T12:00Z`).getUTCDay()+6)%7))):days;const move=(n:number)=>{if(view==='day')setDay(shift(day,n));else if(view==='week')setDay(shift(day,n*7));else{const x=new Date(`${day.slice(0,7)}-01T12:00:00Z`);x.setUTCMonth(x.getUTCMonth()+n);setDay(x.toISOString().slice(0,10))}};
 return <main className="page"><PageHeading eyebrow={tr(ar,'CLINIC SCHEDULE','جدول العيادة')} title={tr(ar,'Appointments','المواعيد')} subtitle={tr(ar,'A clear view of every chair and clinician. Times shown in Cairo.','نظرة واضحة على كل كرسي وطبيب. التوقيت حسب القاهرة.')} action={canWrite(session.role)?<button className="btn btn-primary" onClick={()=>setEditing(true)} data-testid="button-new-appointment"><Plus size={16}/>{tr(ar,'New appointment','موعد جديد')}</button>:undefined}/><div className="care-toolbar"><div className="care-actions"><button className="btn btn-outline" onClick={()=>move(-1)} aria-label={tr(ar,'Previous','السابق')} data-testid="button-calendar-previous"><ChevronLeft size={16}/></button><button className="btn btn-outline" onClick={()=>setDay(cairoDay(new Date()))} data-testid="button-calendar-today">{tr(ar,'Today','اليوم')}</button><button className="btn btn-outline" onClick={()=>move(1)} aria-label={tr(ar,'Next','التالي')} data-testid="button-calendar-next"><ChevronRight size={16}/></button><strong className="care-title" style={{marginInlineStart:9}}>{dateText(`${day}T12:00:00Z`,ar,{month:'long',year:'numeric',day:view==='day'?'numeric':undefined})}</strong></div><div className="care-segment">{(['day','week','month'] as const).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)} data-testid={`button-view-${v}`}>{tr(ar,label(v),{day:'يوم',week:'أسبوع',month:'شهر'}[v])}</button>)}</div></div>{q.isLoading?<State kind="loading"/>:q.isError?<State kind="error" onRetry={()=>q.refetch()}/>:<section className="care-panel"><div className="care-cal">{calendarDays.map((d,i)=><div className={`care-day ${d===cairoDay(new Date())?'current':''} ${d<r.from||d>=r.to?'outside':''}`} key={`${d}-${i}`}><strong>{dateText(`${d}T12:00:00Z`,ar,{weekday:'short',day:'numeric',month:undefined,year:undefined})}</strong>{q.data?.filter(a=>cairoDay(new Date(a.startsAt))===d).sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).map(a=><Link href={`/appointments/${a.id}`} key={a.id} className={`care-event ${a.status==='cancelled'?'cancelled':''}`} title={`${a.patientName} · ${a.treatment}`} data-testid={`link-appointment-${a.id}`}>{dateText(a.startsAt,ar,{hour:'2-digit',minute:'2-digit',day:undefined,month:undefined,year:undefined})} {a.patientName}</Link>)}</div>)}</div>{!q.data?.length&&<div style={{textAlign:'center',padding:27}} className="care-muted"><CalendarDays size={26} style={{margin:'0 auto 9px'}}/>{tr(ar,'No appointments in this period.','لا توجد مواعيد في هذه الفترة.')}</div>}</section>}{editing&&<AppointmentForm session={session} initialDay={day} onClose={()=>setEditing(false)} onSaved={id=>{setEditing(false);navigate(`/appointments/${id}`)}}/>}</main>}

export function AppointmentDetail({session}:{session:StaffSession}){
 const id=Number(useParams<{id:string}>().id),{language}=useLocale(),ar=language==='ar',qc=useQueryClient();
 const [,navigate]=useLocation();
 const q=useGetAppointment(id,{query:{enabled:id>0,queryKey:getGetAppointmentQueryKey(id)}}),cancel=useCancelAppointment();
 const patientId=q.data?.patientId||0;
 const visits=useListPatientVisits(patientId,{query:{enabled:patientId>0&&canClinical(session.role),queryKey:getListPatientVisitsQueryKey(patientId)}});
 const linkedVisit=visits.data?.find(v=>v.appointmentId===id);
 const [editing,setEditing]=useState(false),[error,setError]=useState('');
 const visitCreate=useCreatePatientVisit();
 const handleCancel=async()=>{
  const reason=window.prompt(tr(ar,'Reason for cancellation (optional)','سبب الإلغاء (اختياري)'));
  if(reason===null||!window.confirm(tr(ar,'Cancel this appointment?','هل تريد إلغاء هذا الموعد؟')))return;
  try{await cancel.mutateAsync({appointmentId:id,data:{reason}});invalidateCare(qc,patientId,id)}
  catch(e){setError(errorText(e,ar))}
 };
 return <main className="page">
  <div style={{marginBottom:22}}><BackLink href="/appointments" label={tr(ar,'Schedule','الجدول')}/></div>
  {q.isLoading?<State kind="loading"/>:q.isError?<State kind="error" onRetry={()=>q.refetch()}/>:q.data&&<>
   <PageHeading eyebrow={`${tr(ar,'APPOINTMENT','موعد')} / ${q.data.patientCode}`} title={q.data.patientName} subtitle={dateText(q.data.startsAt,ar,{weekday:'long',hour:'2-digit',minute:'2-digit'})} action={<span className={`care-pill ${q.data.status==='cancelled'?'warn':''}`}>{careLabel(q.data.status,ar)}</span>}/>
   <div className="care-grid">
    <section className="care-panel"><div className="care-kicker">{tr(ar,'VISIT DETAILS','تفاصيل الزيارة')}</div>
     {[[tr(ar,'Treatment','العلاج'),q.data.treatment],[tr(ar,'Doctor','الطبيب'),q.data.doctorName],[tr(ar,'Chair','الكرسي'),q.data.chair||'—'],[tr(ar,'Start','البداية'),dateText(q.data.startsAt,ar,{hour:'2-digit',minute:'2-digit'})],[tr(ar,'End','النهاية'),dateText(q.data.endsAt,ar,{hour:'2-digit',minute:'2-digit'})],[tr(ar,'Notes','ملاحظات'),q.data.notes||'—'],...(q.data.cancelReason?[[tr(ar,'Cancellation reason','سبب الإلغاء'),q.data.cancelReason]]:[])].map(([k,v])=><div className="care-row" key={k}><span className="care-muted">{k}</span><strong style={{fontSize:13,textAlign:'end'}}>{v}</strong></div>)}
    </section>
    <aside className="care-panel"><div className="care-kicker">{tr(ar,'NEXT STEPS','الخطوة التالية')}</div><div className="care-stack">
     <Link href={`/patients/${patientId}`} className="btn btn-outline" data-testid="link-appointment-patient">{tr(ar,'Patient profile','ملف المريض')}</Link>
     {canClinical(session.role)&&<Link href={`/patients/${patientId}/clinical`} className="btn btn-outline" data-testid="link-appointment-clinical">{tr(ar,'Clinical record','السجل الطبي')}</Link>}
     {canWrite(session.role)&&q.data.status!=='cancelled'&&<button className="btn btn-outline" onClick={()=>setEditing(true)} data-testid="button-edit-appointment">{tr(ar,'Edit appointment','تعديل الموعد')}</button>}
     {canClinical(session.role)&&visits.isLoading&&<p className="care-muted">{tr(ar,'Checking for a linked visit…','جارٍ التحقق من الزيارة المرتبطة…')}</p>}
     {canClinical(session.role)&&visits.isError&&<State kind="error" description={tr(ar,'Could not check linked visits.','تعذر التحقق من الزيارات المرتبطة.')} onRetry={()=>visits.refetch()}/>}
     {canClinical(session.role)&&linkedVisit&&<Link href={`/visits/${linkedVisit.id}`} className="btn btn-primary" data-testid="link-appointment-visit">{tr(ar,'Open linked visit','فتح الزيارة المرتبطة')}</Link>}
     {['owner','dentist'].includes(session.role)&&q.data.status!=='cancelled'&&!linkedVisit&&!visits.isLoading&&!visits.isError&&<button className="btn btn-primary" onClick={async()=>{
      try{const visit=await visitCreate.mutateAsync({patientId,data:{appointmentId:id}});invalidateCare(qc,patientId,id,visit.id);navigate(`/visits/${visit.id}`)}
      catch(e){setError(errorText(e,ar));void visits.refetch()}
     }} disabled={visitCreate.isPending} data-testid="button-start-visit">{tr(ar,'Start visit','بدء الزيارة')}</button>}
     {canWrite(session.role)&&q.data.status!=='cancelled'&&<button className="btn btn-outline" onClick={handleCancel} disabled={cancel.isPending} data-testid="button-cancel-appointment">{tr(ar,'Cancel appointment','إلغاء الموعد')}</button>}
     {error&&<InlineError message={error}/>}
    </div></aside>
   </div>
   {editing&&<AppointmentForm session={session} appointment={q.data} onClose={()=>setEditing(false)} onSaved={()=>setEditing(false)}/>}
  </>}
 </main>
}
