import { useGetDashboard, getGetDashboardQueryKey } from '@workspace/api-client-react';
import { Activity, ArrowUpRight, CalendarDays, CircleDollarSign, UserRound, UsersRound, WalletCards } from 'lucide-react';
import { Link } from 'wouter';
import { PageHeading, SectionTitle, State } from '@/components/clinic-ui';
import { useLocale, formatMoney, formatDate } from '@/lib/locale';
import type { StaffSession } from '@workspace/api-client-react';

export default function Dashboard({session}:{session:StaffSession}){const {t,language}=useLocale();const q=useGetDashboard({query:{queryKey:getGetDashboardQueryKey(),refetchInterval:60000}});const financial=['owner','manager','accountant'].includes(session.role);return <main className="page"><PageHeading eyebrow={t('todayLabel')} title={`${t('goodMorning')}, ${session.name.split(' ')[0]}.`} subtitle={t('todaySub')} action={<div className="care-actions">{session.role!=='accountant'&&<Link href="/appointments" className="btn btn-primary" data-testid="link-dashboard-schedule"><CalendarDays size={16}/>{t('appointments')}</Link>}{session.role!=='accountant'&&<Link href="/patients" className="btn btn-outline" data-testid="link-dashboard-patients"><UsersRound size={16}/>{t('patients')}</Link>}</div>}/>{q.isLoading?<State kind="loading"/>:q.isError?<State kind="error" onRetry={()=>q.refetch()}/>:q.data&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:13,marginBottom:23}}>{[
  {key:'appointments' as const,value:q.data.todayAppointments,icon:CalendarDays,tone:'#e9f3ee'},
  {key:'patientsToday' as const,value:q.data.todayPatients,icon:UserRound,tone:'#e9f0f2'},
  ...(financial?[{key:'revenue' as const,value:q.data.todayRevenue === null ? '—' : formatMoney(q.data.todayRevenue,language),icon:CircleDollarSign,tone:'#fff0e7'},{key:'netRevenue' as const,value:q.data.netRevenue === null ? '—' : formatMoney(q.data.netRevenue,language),icon:WalletCards,tone:'#f3f1e9'}]:[])
].map(({key,value,icon:Icon,tone})=><div className="panel" style={{padding:20,minHeight:137}} key={key} data-testid={`metric-${key}`}><div style={{width:34,height:34,display:'grid',placeItems:'center',background:tone,borderRadius:10,color:'#30666a',marginBottom:16}}><Icon size={17}/></div><div className="display" style={{fontSize:28,fontWeight:800,lineHeight:1}}>{value}</div><div className="subtle" style={{marginTop:9}}>{t(key)}</div></div>)}</div>
<div style={{display:'grid',gridTemplateColumns:'minmax(0,1.75fr) minmax(270px,.8fr)',gap:20}} className="dashboard-grid"><section className="panel" style={{padding:24,minWidth:0}}><SectionTitle title={t('schedule')} sub={t('scheduleSub')} icon={<CalendarDays size={18} color="#367c77"/>}/>{q.data.appointments.length===0?<div className="empty"><div className="empty-icon"><CalendarDays size={23}/></div><h3>{t('noAppointments')}</h3><p className="subtle">{t('noAppointmentsSub')}</p></div>:<div>{q.data.appointments.map(a=><div key={a.id} style={{display:'grid',gridTemplateColumns:'65px minmax(0,1fr) auto',alignItems:'center',gap:13,padding:'16px 0',borderTop:'1px solid #e9eeea'}} data-testid={`row-appointment-${a.id}`}><div style={{fontWeight:800,fontSize:13,color:'#285e62'}}>{formatDate(a.startsAt,language,{hour:'numeric',minute:'2-digit',year:undefined,month:undefined,day:undefined})}</div><div style={{minWidth:0}}><div style={{fontWeight:800,fontSize:13,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{a.patientName}</div><div className="subtle" style={{marginTop:3}}>{a.treatment} · {a.doctorName}</div></div><span className={`badge ${['cancelled','no-show'].includes(a.status)?'warn':''}`}>{a.status.replace(/_/g,' ')}</span></div>)}</div>}</section>
<aside style={{display:'flex',flexDirection:'column',gap:19}}><section className="panel" style={{padding:24,background:'#e5f1eb'}}><SectionTitle title={t('overview')} icon={<Activity size={18} color="#367c77"/>}/>{[
  ['newPatients',q.data.newPatients],['returningPatients',q.data.returningPatients],['followUps',q.data.pendingFollowUps],['cancelled',q.data.cancelledAppointments],['noShows',q.data.noShows]
 ].map(([key,value])=><div key={key} style={{display:'flex',justifyContent:'space-between',padding:'11px 0',borderBottom:'1px solid #c9e0d8',fontSize:12}}><span style={{color:'#4d7370'}}>{key==='followUps'?(language==='ar'?'مسودات التذكير المعلقة':'Pending reminder drafts'):t(key as Parameters<typeof t>[0])}</span><strong style={{color:'#204a50'}}>{value}</strong></div>)}</section>{financial&&<section className="panel" style={{padding:24}}><SectionTitle title={t('revenue')} icon={<ArrowUpRight size={18} color="#367c77"/>}/>{[['expenses',q.data.todayExpenses],['outstanding',q.data.outstandingPayments]].map(([key,value])=><div key={key} style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderTop:'1px solid #e8eeea',fontSize:12}}><span className="subtle">{t(key as Parameters<typeof t>[0])}</span><strong>{typeof value === 'number' ? formatMoney(value,language) : '—'}</strong></div>)}</section>}</aside></div></>}</main>}