import { useState,type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useListSuppliers,useCreateSupplier,useUpdateSupplier,type Supplier } from '@workspace/api-client-react';
import { Plus } from 'lucide-react';
import { PageHeading } from '@/components/clinic-ui';
import { Field,FinanceTabs,Input,Modal,QueryState } from '@/components/ledger-ui';
import { useLocale } from '@/lib/locale';
import { invalidateSuppliers } from '@/lib/ledger';
export default function FinanceSuppliers(){
  const {t,language}=useLocale();const qc=useQueryClient();const q=useListSuppliers();const create=useCreateSupplier();const update=useUpdateSupplier();const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Supplier|null>(null);const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [notes,setNotes]=useState('');
  function start(s?:Supplier){setEditing(s||null);setName(s?.name||'');setPhone(s?.phone||'');setEmail(s?.email||'');setNotes(s?.notes||'');create.reset();update.reset();setOpen(true)}
  function close(){setOpen(false);setEditing(null);setName('');setPhone('');setEmail('');setNotes('')}
  function submit(e:FormEvent){e.preventDefault();const data={name:name.trim(),phone:phone||null,email:email||null,notes:notes||null};if(editing)update.mutate({supplierId:editing.id,data},{onSuccess:()=>{invalidateSuppliers(qc);close()}});else create.mutate({data},{onSuccess:()=>{invalidateSuppliers(qc);close()}})}
  function toggle(s:Supplier){update.mutate({supplierId:s.id,data:{active:!s.active}},{onSuccess:()=>invalidateSuppliers(qc)})}
  return <main className="page"><PageHeading eyebrow={t('finance')} title={t('suppliers')} subtitle={language==='ar'?'جهات الاتصال التي تعتمد عليها العيادة.':'The people who keep the clinic supplied.'} action={<button className="btn btn-primary" onClick={()=>start()} data-testid="button-new-supplier"><Plus size={16}/>{t('newSupplier')}</button>}/><FinanceTabs/><QueryState loading={q.isLoading} error={q.isError} empty={!q.data?.length} retry={()=>q.refetch()}/>{!!q.data?.length&&<div className="panel ledger-list">{q.data.map(s=><div className="ledger-row" key={s.id} data-testid={`row-supplier-${s.id}`}><div><strong>{s.name}</strong><small dir="auto">{[s.phone,s.email].filter(Boolean).join(' · ')||'—'}</small>{s.notes&&<small>{s.notes}</small>}<span className={`badge ${s.active?'':'muted'}`}>{s.active?t('activeLabel'):t('inactiveLabel')}</span></div><div className="ledger-actions"><button className="btn btn-outline" onClick={()=>start(s)} data-testid={`button-edit-supplier-${s.id}`}>{t('edit')}</button><button className="btn btn-soft" disabled={update.isPending} onClick={()=>toggle(s)} data-testid={`button-toggle-supplier-${s.id}`}>{s.active?t('inactiveLabel'):t('activeLabel')}</button></div></div>)}</div>}{update.isError&&!open&&<p role="alert" className="ledger-note">{String((update.error as Error).message)}</p>}
  {open&&<Modal title={editing?t('edit'):t('newSupplier')} onClose={close} onSubmit={submit} pending={create.isPending||update.isPending} error={create.isError||update.isError?String(((create.error||update.error) as Error).message):undefined}><Field label={t('name')}><Input value={name} onChange={setName} required testId="input-supplier-name"/></Field><div className="form-grid"><Field label={t('phone')}><Input value={phone} onChange={setPhone} type="tel" testId="input-supplier-phone"/></Field><Field label={t('email')}><Input value={email} onChange={setEmail} type="email" testId="input-supplier-email"/></Field></div><Field label={t('notes')}><Input value={notes} onChange={setNotes} testId="input-supplier-notes"/></Field></Modal>}</main>
}