import { useState } from 'react';
import { useGetFinanceReport } from '@workspace/api-client-react';
import { PageHeading,State } from '@/components/clinic-ui';
import { DateText,Field,FinanceTabs,Input,Pair } from '@/components/ledger-ui';
import { useLocale } from '@/lib/locale';
import { money } from '@/lib/ledger';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default function FinanceReports(){
  const {t,language}=useLocale();const [from,setFrom]=useState(today().slice(0,7)+'-01');const [to,setTo]=useState(today());const [period,setPeriod]=useState({from:today().slice(0,7)+'-01',to:today()});const q=useGetFinanceReport(period);const r=q.data;
  return <main className="page"><PageHeading eyebrow={t('finance')} title={t('reports')} subtitle={language==='ar'?'إيرادات ومصروفات قابلة للمراجعة يومًا بيوم.':'Revenue and expenses you can trace, day by day.'}/><FinanceTabs/><div className="ledger-toolbar"><Field label={t('from')}><Input value={from} onChange={setFrom} type="date" testId="input-report-from"/></Field><Field label={t('to')}><Input value={to} onChange={setTo} type="date" testId="input-report-to"/></Field><button className="btn btn-primary" disabled={!from||!to||from>to} onClick={()=>setPeriod({from,to})} data-testid="button-apply-report">{t('apply')}</button></div>{q.isLoading?<State kind="loading"/>:q.isError?<State kind="error" onRetry={()=>q.refetch()}/>:r&&<><div className="ledger-grid"><div className="ledger-stat"><span>{t('revenue')}</span><strong>{money(r.revenueCents,language)}</strong></div><div className="ledger-stat"><span>{t('expenses')}</span><strong>{money(r.expenseCents,language)}</strong></div><div className="ledger-stat"><span>{t('net')}</span><strong>{money(r.netCents,language)}</strong></div></div><div className="ledger-split"><section className="panel ledger-section"><h2>{t('daily')}</h2>{r.days.length?r.days.map(d=><div key={d.date} className="ledger-pair"><span><DateText value={d.date}/></span><strong><span style={{color:'#397b68'}}>{money(d.revenueCents,language)}</span> / <span style={{color:'#a46b3d'}}>{money(d.expenseCents,language)}</span></strong></div>):<p className="ledger-note">{t('noRecords')}</p>}</section><div><section className="panel ledger-section"><h2>{t('overview')}</h2><Pair label={t('outstanding')} value={money(r.outstandingCents,language)}/><Pair label={t('overdue')} value={money(r.overdueCents,language)}/><Pair label={t('invoices')} value={r.invoiceCount}/><Pair label={t('balance')} value={r.unpaidInvoiceCount}/></section><section className="panel ledger-section"><h2>{t('byCategory')}</h2>{r.categories.length?r.categories.map(c=><Pair key={c.category} label={c.category} value={money(c.amountCents,language)}/>):<p className="ledger-note">{t('noRecords')}</p>}</section><section className="panel ledger-section"><h2>{t('byMethod')}</h2>{r.methods.length?r.methods.map(m=><Pair key={m.method} label={t(m.method)} value={money(m.amountCents,language)}/>):<p className="ledger-note">{t('noRecords')}</p>}</section></div></div></>}</main>
}