import { useState,type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useListInventoryItems,useCreateInventoryItem,useUpdateInventoryItem,useListStockMovements,useRecordStockMovement,useListSuppliers,getListSuppliersQueryKey,type InventoryItem,type StaffSession,type StockMovementInputReason } from '@workspace/api-client-react';
import { Plus,ArrowDownToLine,ArrowUpFromLine,SlidersHorizontal } from 'lucide-react';
import { PageHeading,State } from '@/components/clinic-ui';
import { DateText,Field,Input,Modal,Pair,QueryState } from '@/components/ledger-ui';
import { useLocale } from '@/lib/locale';
import { egp,invalidateStock,money,toCents } from '@/lib/ledger';
const financeRoles=['owner','manager','accountant'];
function History({item}:{item:InventoryItem}){const {t}=useLocale();const q=useListStockMovements(item.id);return <section className="panel ledger-section"><h2>{t('movements')} · {item.name}</h2>{q.isLoading?<State kind="loading"/>:q.isError?<State kind="error" onRetry={()=>q.refetch()}/>:q.data?.length?q.data.map(m=><div className="ledger-row" key={m.id}><div><strong>{t(m.reason)} · {m.staffName}</strong><small><DateText value={m.occurredAt}/>{m.note&&` · ${m.note}`}</small></div><div className="ledger-money" style={{color:m.delta<0?'#a46b3d':'#397b68'}} dir="ltr">{m.delta>0?'+':''}{m.delta}</div></div>):<p className="ledger-note">{t('noRecords')}</p>}</section>}
export default function Inventory({session}:{session:StaffSession}){
  const {t,language}=useLocale();const qc=useQueryClient();const financial=financeRoles.includes(session.role);const canManage=financial;const q=useListInventoryItems();const suppliers=useListSuppliers({query:{enabled:financial,queryKey:getListSuppliersQueryKey()}});const create=useCreateInventoryItem();const update=useUpdateInventoryItem();const movement=useRecordStockMovement();
  const [filter,setFilter]=useState<'all'|'low'>('all');const [selected,setSelected]=useState<InventoryItem|null>(null);const [editing,setEditing]=useState<InventoryItem|null>(null);const [itemOpen,setItemOpen]=useState(false);const [moveOpen,setMoveOpen]=useState(false);const [reason,setReason]=useState<StockMovementInputReason>('consume');
  const [name,setName]=useState('');const [sku,setSku]=useState('');const [unit,setUnit]=useState('');const [threshold,setThreshold]=useState('0');const [cost,setCost]=useState('');const [supplier,setSupplier]=useState('');const [delta,setDelta]=useState('');const [note,setNote]=useState('');const [validation,setValidation]=useState('');
  function startItem(item?:InventoryItem){setEditing(item||null);setName(item?.name||'');setSku(item?.sku||'');setUnit(item?.unit||'');setThreshold(String(item?.reorderLevel??0));setCost(egp(item?.unitCostCents));setSupplier(item?.supplierId?String(item.supplierId):'');setValidation('');create.reset();update.reset();setItemOpen(true)}
  function closeItem(){setItemOpen(false);setEditing(null);setName('');setSku('');setUnit('');setThreshold('0');setCost('');setSupplier('');setValidation('')}
  function submitItem(e:FormEvent){e.preventDefault();const cents=cost.trim()?toCents(cost):null;if(!Number.isSafeInteger(Number(threshold))||Number(threshold)<0||(cost.trim()&&cents===null)){setValidation(t('invalidAmount'));return}const data={name:name.trim(),sku:sku.trim(),unit:unit.trim(),reorderLevel:Number(threshold),unitCostCents:cents,supplierId:supplier?Number(supplier):null};if(editing)update.mutate({itemId:editing.id,data},{onSuccess:()=>{invalidateStock(qc,editing.id);closeItem()}});else create.mutate({data},{onSuccess:()=>{invalidateStock(qc);closeItem()}})}
  function startMove(item:InventoryItem,kind:StockMovementInputReason){setSelected(item);setReason(kind);setDelta('');setNote('');setValidation('');movement.reset();setMoveOpen(true)}
  function closeMove(){setMoveOpen(false);setDelta('');setNote('');setValidation('');movement.reset()}
  function submitMove(e:FormEvent){e.preventDefault();if(!selected)return;const qty=Number(delta);if(!Number.isSafeInteger(qty)||qty===0||(reason!=='adjust'&&qty<1)||(reason==='consume'&&qty>selected.quantityOnHand)){setValidation(language==='ar'?'أدخل كمية صحيحة ضمن المتاح.':'Enter a valid quantity within stock on hand.');return}movement.mutate({itemId:selected.id,data:{reason,delta:reason==='consume'?-qty:qty,note:note||null}},{onSuccess:()=>{invalidateStock(qc,selected.id);closeMove()}})}
  function toggle(item:InventoryItem){update.mutate({itemId:item.id,data:{active:!item.active}},{onSuccess:()=>invalidateStock(qc,item.id)})}
  const items=q.data?.filter(i=>filter==='all'||i.lowStock)||[];
  return <main className="page"><PageHeading eyebrow={t('workspace')} title={t('inventory')} subtitle={language==='ar'?'الكميات المتاحة وحركة الأصناف في مكان واحد.':'What is on hand, what needs attention, and every stock movement.'} action={canManage?<button className="btn btn-primary" onClick={()=>startItem()} data-testid="button-new-item"><Plus size={16}/>{t('newItem')}</button>:undefined}/>
    <div className="ledger-tabs"><button className={`btn ${filter==='all'?'btn-primary':'btn-outline'}`} onClick={()=>setFilter('all')} data-testid="button-inventory-all">{t('inventory')}{q.data?` · ${q.data.length}`:''}</button><button className={`btn ${filter==='low'?'btn-primary':'btn-outline'}`} onClick={()=>setFilter('low')} data-testid="button-inventory-low">{t('lowStock')}{q.data?` · ${q.data.filter(i=>i.lowStock).length}`:''}</button></div>
    <QueryState loading={q.isLoading} error={q.isError} empty={!items.length} retry={()=>q.refetch()}/>{!!items.length&&<div className="panel ledger-list">{items.map(item=><div key={item.id} data-testid={`row-inventory-${item.id}`}><div className="ledger-row"><div style={{minWidth:0}}><strong>{item.name}</strong><small>{item.sku} · {item.unit}{financial&&item.supplierName?` · ${item.supplierName}`:''}</small><span className={`badge ${item.lowStock?'warn':item.active?'':'muted'}`}>{item.lowStock?t('lowStock'):item.active?t('activeLabel'):t('inactiveLabel')}</span></div><div style={{textAlign:'end'}}><div className="ledger-money">{item.quantityOnHand} <span className="subtle">{item.unit}</span></div><small>{t('threshold')}: {item.reorderLevel}</small>{financial&&item.unitCostCents!==null&&<small>{t('cost')}: {money(item.unitCostCents,language)}</small>}</div></div><div style={{display:'flex',gap:7,flexWrap:'wrap',padding:'0 18px 15px'}}><button className="btn btn-soft" onClick={()=>setSelected(selected?.id===item.id?null:item)} data-testid={`button-history-${item.id}`}>{t('movements')}</button>{canManage&&<button className="btn btn-outline" onClick={()=>startMove(item,'receive')} data-testid={`button-receive-${item.id}`}><ArrowDownToLine size={14}/>{t('receive')}</button>}<button className="btn btn-outline" onClick={()=>startMove(item,'consume')} data-testid={`button-consume-${item.id}`}><ArrowUpFromLine size={14}/>{t('consume')}</button>{canManage&&<><button className="btn btn-outline" onClick={()=>startMove(item,'adjust')} data-testid={`button-adjust-${item.id}`}><SlidersHorizontal size={14}/>{t('adjust')}</button><button className="btn btn-outline" onClick={()=>startItem(item)} data-testid={`button-edit-item-${item.id}`}>{t('edit')}</button><button className="btn btn-outline" disabled={update.isPending} onClick={()=>toggle(item)} data-testid={`button-toggle-item-${item.id}`}>{item.active?t('inactiveLabel'):t('activeLabel')}</button></>}</div>{selected?.id===item.id&&!moveOpen&&<div style={{padding:'0 16px 15px'}}><History item={item}/></div>}</div>)}</div>}{update.isError&&!itemOpen&&<p role="alert" className="ledger-note">{String((update.error as Error).message)}</p>}
    {itemOpen&&canManage&&<Modal title={editing?t('edit'):t('newItem')} onClose={closeItem} onSubmit={submitItem} pending={create.isPending||update.isPending} error={validation||((create.error||update.error) instanceof Error?String(((create.error||update.error) as Error).message):'')}><div className="form-grid"><Field label={t('name')}><Input value={name} onChange={setName} required testId="input-item-name"/></Field><Field label={t('sku')}><Input value={sku} onChange={setSku} required testId="input-item-sku"/></Field></div><div className="form-grid"><Field label={t('unit')}><Input value={unit} onChange={setUnit} required testId="input-item-unit"/></Field><Field label={t('threshold')}><Input value={threshold} onChange={setThreshold} type="number" min="0" step="1" required testId="input-item-threshold"/></Field></div><div className="form-grid"><Field label={t('cost')}><Input value={cost} onChange={setCost} testId="input-item-cost"/></Field><Field label={t('supplier')}><select className="input" value={supplier} onChange={e=>setSupplier(e.target.value)} data-testid="select-item-supplier"><option value="">—</option>{suppliers.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div>{suppliers.isError&&<p role="alert" className="ledger-note">{t('error')}</p>}</Modal>}
    {moveOpen&&selected&&<Modal title={t(reason)} onClose={closeMove} onSubmit={submitMove} pending={movement.isPending} error={validation|| (movement.isError?String((movement.error as Error).message):'')}><p className="ledger-note">{selected.name}</p><Pair label={t('stock')} value={`${selected.quantityOnHand} ${selected.unit}`}/><Field label={`${t('quantity')}${reason==='adjust'?' (+ / −)':''}`}><Input value={delta} onChange={setDelta} type="number" step="1" required testId="input-movement-delta"/></Field><Field label={t('notes')}><Input value={note} onChange={setNote} testId="input-movement-note"/></Field></Modal>}
  </main>
}