import { useState, type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getListMarketingCampaignsQueryKey, getGetMarketingReportQueryKey, useListMarketingCampaigns, useGetMarketingReport, useCreateMarketingCampaign, useUpdateMarketingCampaign, useDisableMarketingCampaign, type StaffSession, type Campaign, type CampaignInputStatus } from '@workspace/api-client-react';
import { BackLink, InlineError, PageHeading, State } from '@/components/clinic-ui';
import { useLocale } from '@/lib/locale';
import { careLabel as baseLabel, dateText, errorText, tr } from '@/lib/care';

const careLabel=(value:string,ar:boolean)=>ar?({paused:'متوقفة مؤقتًا',ended:'منتهية',disabled:'معطلة'} as Record<string,string>)[value]||baseLabel(value,ar):baseLabel(value,ar);

type Form={code:string;channel:string;startDate:string;endDate:string;status:CampaignInputStatus};
const empty:Form={code:'',channel:'',startDate:'',endDate:'',status:'active'};
const statuses:CampaignInputStatus[]=['active','paused','ended'];
export default function Marketing({session}:{session?:StaffSession}){
 const {language}=useLocale(),ar=language==='ar',qc=useQueryClient(),writable=!!session&&['owner','manager'].includes(session.role);
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[applied,setApplied]=useState<{from?:string;to?:string}>({});
 const list=useListMarketingCampaigns(),report=useGetMarketingReport(applied,{query:{queryKey:getGetMarketingReportQueryKey(applied)}}),create=useCreateMarketingCampaign(),update=useUpdateMarketingCampaign(),disable=useDisableMarketingCampaign();
 const [editing,setEditing]=useState(0),[form,setForm]=useState<Form>(empty),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const refresh=()=>{void qc.invalidateQueries({queryKey:getListMarketingCampaignsQueryKey()});void qc.invalidateQueries({queryKey:getGetMarketingReportQueryKey().slice(0,1)})};
 const change=<K extends keyof Form>(key:K,value:Form[K])=>setForm(f=>({...f,[key]:value}));
 function begin(c:Campaign){setEditing(c.id);setForm({code:c.code,channel:c.channel,startDate:c.startDate?.slice(0,10)||'',endDate:c.endDate?.slice(0,10)||'',status:c.status==='disabled'?'ended':c.status});setError('');document.getElementById('campaign-form')?.scrollIntoView({behavior:'smooth'})}
 async function save(e:FormEvent){e.preventDefault();setError('');setSaved('');if(form.startDate&&form.endDate&&form.startDate>form.endDate){setError(tr(ar,'End date must be after start date.','يجب أن يكون تاريخ الانتهاء بعد تاريخ البدء.'));return}try{const data={code:form.code.trim(),channel:form.channel.trim(),startDate:form.startDate||null,endDate:form.endDate||null,status:form.status};if(editing)await update.mutateAsync({campaignId:editing,data});else await create.mutateAsync({data});refresh();setEditing(0);setForm(empty);setSaved(tr(ar,'Campaign saved.','تم حفظ الحملة.'))}catch(e){setError(errorText(e,ar))}}
 async function disableCampaign(c:Campaign){if(!window.confirm(tr(ar,`Disable campaign ${c.code}? Existing referral totals will remain.`,`هل تريد تعطيل الحملة ${c.code}؟ ستبقى إحصاءات الإحالات السابقة.`)))return;setError('');setSaved('');try{await disable.mutateAsync({campaignId:c.id});refresh();if(editing===c.id){setEditing(0);setForm(empty)}setSaved(tr(ar,'Campaign disabled.','تم تعطيل الحملة.'))}catch(e){setError(errorText(e,ar))}}
 function apply(e:FormEvent){e.preventDefault();if((from&&!to)||(!from&&to)||from&&to&&from>to){setError(tr(ar,'Choose a valid start and end date, or leave both blank.','اختر تاريخ بداية ونهاية صحيحين، أو اتركهما فارغين.'));return}setError('');setApplied(from&&to?{from,to}:{})}
 return <main className="page care-hub"><BackLink href="/dashboard" label={tr(ar,'Dashboard','لوحة التحكم')}/><PageHeading eyebrow={tr(ar,'GROWTH / REFERRALS','النمو / الإحالات')} title={tr(ar,'Marketing','التسويق')} subtitle={tr(ar,'Manage campaign sources and understand where new patients found the clinic.','أدر مصادر الحملات واعرف كيف وصل المرضى الجدد إلى العيادة.')}/>{saved&&<div className="care-hub-note" role="status">{saved}</div>}{error&&<InlineError message={error}/>}
 <section className="care-hub-card"><h2>{tr(ar,'Referral report','تقرير الإحالات')}</h2><form className="care-hub-actions" onSubmit={apply} style={{alignItems:'end',marginBottom:18}}><label className="care-field">{tr(ar,'From','من')}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="care-field">{tr(ar,'To','إلى')}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn btn-outline">{tr(ar,'Apply dates','تطبيق الفترة')}</button></form>{report.isLoading?<State kind="loading"/>:report.isError?<State kind="error" onRetry={()=>report.refetch()}/>:report.data&&<><div className="care-hub-note">{tr(ar,'Total patient referrals','إجمالي إحالات المرضى')} <strong className="care-hub-number">{report.data.totalReferrals.toLocaleString(ar?'ar-EG':'en-EG')}</strong></div><div className="care-hub-grid" style={{marginTop:16}}><div><h2>{tr(ar,'Campaign sources','مصادر الحملات')}</h2>{report.data.campaigns.length?<div className="care-hub-list">{report.data.campaigns.map(c=><div className="care-hub-item" key={c.id}><span><strong>{c.code}</strong><small>{c.channel} · {careLabel(c.status,ar)}</small></span><strong>{c.referrals.toLocaleString(ar?'ar-EG':'en-EG')}</strong></div>)}</div>:<State kind="empty" title={tr(ar,'No campaign sources','لا توجد مصادر حملات')}/>}</div><div><h2>{tr(ar,'Other referral sources','مصادر إحالة أخرى')}</h2>{report.data.unattributedSources.length?<div className="care-hub-list">{report.data.unattributedSources.map(s=><div className="care-hub-item" key={s.source}><strong>{s.source}</strong><strong>{s.referrals.toLocaleString(ar?'ar-EG':'en-EG')}</strong></div>)}</div>:<State kind="empty" title={tr(ar,'No other sources','لا توجد مصادر أخرى')}/>}</div></div></>}</section>
 <section className="care-hub-card"><h2>{tr(ar,'Campaigns','الحملات')}</h2>{list.isLoading?<State kind="loading"/>:list.isError?<State kind="error" onRetry={()=>list.refetch()}/>:!list.data?.length?<State kind="empty" title={tr(ar,'No campaigns yet','لا توجد حملات بعد')} description={tr(ar,'Create a campaign code to track matching patient referral sources.','أنشئ رمز حملة لتتبع مصادر إحالات المرضى المطابقة.')}/>:<div className="care-hub-list">{list.data.map(c=><div className="care-hub-item" key={c.id}><div><strong>{c.code} <span className="care-pill">{careLabel(c.status,ar)}</span></strong><small>{c.channel} · {c.startDate?dateText(c.startDate,ar):'—'} – {c.endDate?dateText(c.endDate,ar):'—'}</small></div>{writable&&c.status!=='disabled'&&<div className="care-hub-actions"><button className="btn btn-outline" onClick={()=>begin(c)}>{tr(ar,'Edit','تعديل')}</button><button className="btn btn-outline" disabled={disable.isPending} onClick={()=>disableCampaign(c)}>{tr(ar,'Disable','تعطيل')}</button></div>}</div>)}</div>}</section>
 {writable&&<section className="care-hub-card" id="campaign-form"><h2>{editing?tr(ar,'Edit campaign','تعديل الحملة'):tr(ar,'Create campaign','إنشاء حملة')}</h2><p className="subtle">{tr(ar,'The code is matched to the patient referral source; use the exact code you share.','يُطابق الرمز بمصدر إحالة المريض؛ استخدم الرمز الذي تشاركه كما هو.')}</p><form className="care-hub-form" onSubmit={save}><label className="care-field">{tr(ar,'Campaign code','رمز الحملة')}<input required maxLength={120} value={form.code} onChange={e=>change('code',e.target.value)}/></label><label className="care-field">{tr(ar,'Channel','القناة')}<input required maxLength={80} value={form.channel} onChange={e=>change('channel',e.target.value)}/></label><label className="care-field">{tr(ar,'Start date','تاريخ البداية')}<input type="date" value={form.startDate} onChange={e=>change('startDate',e.target.value)}/></label><label className="care-field">{tr(ar,'End date','تاريخ الانتهاء')}<input type="date" value={form.endDate} onChange={e=>change('endDate',e.target.value)}/></label><label className="care-field">{tr(ar,'Status','الحالة')}<select value={form.status} onChange={e=>change('status',e.target.value as CampaignInputStatus)}>{statuses.map(s=><option key={s} value={s}>{careLabel(s,ar)}</option>)}</select></label>{error&&<InlineError message={error}/>}<div className="care-hub-actions"><button className="btn btn-primary" disabled={create.isPending||update.isPending}>{tr(ar,'Save campaign','حفظ الحملة')}</button>{!!editing&&<button type="button" className="btn btn-outline" onClick={()=>{setEditing(0);setForm(empty);setError('')}}>{tr(ar,'Cancel edit','إلغاء التعديل')}</button>}</div></form></section>}</main>;
}