import { useEffect, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetPatientsQueryKey, useCreatePatient, useGetPatients, type PatientInput, type StaffSession } from '@workspace/api-client-react';
import { ArrowLeft, ArrowRight, Plus, Search, UserRound, X } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { PageHeading, State, NextArrow } from '@/components/clinic-ui';
import { PatientForm } from '@/components/patient-form';
import { useLocale } from '@/lib/locale';

export default function Patients({session}:{session:StaffSession}){const {t,language}=useLocale();const [search,setSearch]=useState('');const [debounced,setDebounced]=useState('');const [offset,setOffset]=useState(0);const [createOpen,setCreateOpen]=useState(false);const [,navigate]=useLocation();const qc=useQueryClient();const canEdit=['owner','manager','reception','dentist'].includes(session.role);useEffect(()=>{const id=setTimeout(()=>{setDebounced(search.trim());setOffset(0)},260);return()=>clearTimeout(id)},[search]);const q=useGetPatients({search:debounced||undefined,limit:20,offset});const create=useCreatePatient();function save(data:PatientInput){create.mutate({data},{onSuccess:patient=>{qc.invalidateQueries({queryKey:getGetPatientsQueryKey()});setCreateOpen(false);navigate(`/patients/${patient.id}`)}})}
return <main className="page"><PageHeading eyebrow={t('directory')} title={t('patientDirectory')} subtitle={t('patientDirectorySub')} action={canEdit?<button className="btn btn-primary" onClick={()=>{create.reset();setCreateOpen(true)}} data-testid="button-add-patient"><Plus size={16}/>{t('addPatient')}</button>:undefined}/><div className="panel" style={{overflow:'hidden'}}><div style={{padding:'20px 22px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:15,borderBottom:'1px solid #e7ece7'}}><div style={{position:'relative',width:'min(100%,440px)'}}><Search size={17} style={{position:'absolute',insetInlineStart:13,top:13,color:'#72918b'}}/><input className="input" type="search" style={{paddingInlineStart:39}} placeholder={t('searchPlaceholder')} aria-label={t('searchPatients')} value={search} onChange={e=>setSearch(e.target.value)} data-testid="input-search-patients"/></div><span className="subtle hide-mobile">{t('patients')}</span></div>{q.isLoading?<div style={{padding:20}}><State kind="loading"/></div>:q.isError?<div style={{padding:20}}><State kind="error" onRetry={()=>q.refetch()}/></div>:q.data?.length===0?<State kind="empty" title={t('noPatients')} description={t('noPatientsSub')}/>:<><div>{q.data?.map(p=><Link key={p.id} href={`/patients/${p.id}`} data-testid={`link-patient-${p.id}`} style={{display:'grid',gridTemplateColumns:'40px minmax(0,1fr) minmax(95px,.55fr) minmax(100px,.65fr) auto',gap:14,alignItems:'center',padding:'17px 22px',borderBottom:'1px solid #edf0ec',textDecoration:'none',color:'inherit',transition:'background .2s'}} className="patient-row"><div className="avatar" style={{background:'#e5f1eb'}}><UserRound size={17}/></div><div style={{minWidth:0}}><div style={{fontWeight:800,fontSize:13,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}} data-testid={`text-patient-name-${p.id}`}>{p.fullName}</div><div className="subtle" style={{marginTop:4,fontFamily:'monospace',fontSize:11}}>{p.patientCode}</div></div><div className="patient-extra" dir="ltr" style={{fontSize:12,color:'#446467'}}>{p.phone}</div><div className="patient-extra"><span className={`badge ${p.status==='active'?'':'muted'}`}>{t(p.status)}</span></div><NextArrow/></Link>)}</div><div style={{padding:'15px 22px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><span className="subtle">{t('page')} {Math.floor(offset/20)+1}</span><div style={{display:'flex',gap:8}}><button className="btn btn-outline" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))} data-testid="button-previous-patients">{language==='ar'?<ArrowRight size={15}/>:<ArrowLeft size={15}/>}<span className="hide-mobile">{t('previous')}</span></button><button className="btn btn-outline" disabled={(q.data?.length||0)<20} onClick={()=>setOffset(offset+20)} data-testid="button-next-patients"><span className="hide-mobile">{t('next')}</span>{language==='ar'?<ArrowLeft size={15}/>:<ArrowRight size={15}/>}</button></div></div></>}</div>
{createOpen&&<div role="dialog" aria-modal="true" aria-label={t('newPatient')} style={{position:'fixed',inset:0,zIndex:60,background:'#102d33b0',overflowY:'auto',padding:'20px'}} onClick={e=>{if(e.target===e.currentTarget)setCreateOpen(false)}}><div style={{width:'min(100%,760px)',margin:'30px auto',background:'#f6f5ef',borderRadius:20,padding:'clamp(18px,3vw,35px)',boxShadow:'0 28px 80px #102d3355'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'start',marginBottom:25}}><div><div className="eyebrow">{t('directory')}</div><h2 className="display" style={{fontSize:30,margin:'5px 0'}}>{t('newPatient')}</h2></div><button className="btn btn-outline" onClick={()=>setCreateOpen(false)} aria-label={t('cancel')} data-testid="button-close-patient-form"><X size={18}/></button></div><PatientForm administrativeOnly={session.role==='reception'} onSave={data=>save(data as PatientInput)} pending={create.isPending} error={create.isError?String((create.error as Error)?.message||t('error')):undefined}/></div></div>}</main>}