import { useState, type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useParams } from 'wouter';
import { getListPatientAlignerCoursesQueryKey, getGetPatientAlignerCourseQueryKey, getListPatientOrthodonticCasesQueryKey, getListPatientVisitsQueryKey, useListPatientAlignerCourses, useGetPatientAlignerCourse, useCreatePatientAlignerCourse, useCreateAlignerTray, useUpdateAlignerTray, useListPatientOrthodonticCases, useListPatientVisits, type StaffSession, type AlignerTray, type TrayStatus } from '@workspace/api-client-react';
import { BackLink, InlineError, PageHeading, State } from '@/components/clinic-ui';
import { useLocale } from '@/lib/locale';
import { careLabel as baseLabel, dateText, errorText, tr } from '@/lib/care';

const careLabel=(value:string,ar:boolean)=>ar?({planned:'مخطط',delivered:'تم التسليم',wearing:'قيد الارتداء',paused:'متوقف مؤقتًا'} as Record<string,string>)[value]||baseLabel(value,ar):baseLabel(value,ar);

type TrayForm={sequence:string;plannedDate:string;deliveredDate:string;status:TrayStatus;wearNotes:string;visitId:string};
const emptyTray:TrayForm={sequence:'',plannedDate:'',deliveredDate:'',status:'planned',wearNotes:'',visitId:''};
const statuses:TrayStatus[]=['planned','delivered','wearing','completed','paused'];
export default function PatientAligners({session}:{session:StaffSession}){
 const id=Number(useParams<{id:string}>().id),{language}=useLocale(),ar=language==='ar',qc=useQueryClient(),writable=['owner','dentist'].includes(session.role);
 const courses=useListPatientAlignerCourses(id,{query:{enabled:id>0,queryKey:getListPatientAlignerCoursesQueryKey(id)}}),cases=useListPatientOrthodonticCases(id,{query:{enabled:id>0,queryKey:getListPatientOrthodonticCasesQueryKey(id)}}),visits=useListPatientVisits(id,{query:{enabled:id>0&&writable,queryKey:getListPatientVisitsQueryKey(id)}});
 const [selected,setSelected]=useState(0),course=useGetPatientAlignerCourse(id,selected,{query:{enabled:id>0&&selected>0,queryKey:getGetPatientAlignerCourseQueryKey(id,selected)}}),createCourse=useCreatePatientAlignerCourse(),createTray=useCreateAlignerTray(),updateTray=useUpdateAlignerTray();
 const [title,setTitle]=useState(''),[caseId,setCaseId]=useState(''),[tray,setTray]=useState<TrayForm>(emptyTray),[editingTray,setEditingTray]=useState(0),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const refresh=(courseId:number)=>{void qc.invalidateQueries({queryKey:getListPatientAlignerCoursesQueryKey(id)});void qc.invalidateQueries({queryKey:getGetPatientAlignerCourseQueryKey(id,courseId)})};
 const change=<K extends keyof TrayForm>(key:K,value:TrayForm[K])=>setTray(t=>({...t,[key]:value}));
 async function saveCourse(e:FormEvent){e.preventDefault();setError('');setSaved('');try{const result=await createCourse.mutateAsync({patientId:id,data:{caseId:Number(caseId),title:title.trim()}});refresh(result.id);setSelected(result.id);setTitle('');setCaseId('');setSaved(tr(ar,'Course created.','تم إنشاء المسار.'))}catch(e){setError(errorText(e,ar))}}
 async function saveTray(e:FormEvent){e.preventDefault();setError('');setSaved('');try{const data={plannedDate:tray.plannedDate||null,deliveredDate:tray.deliveredDate||null,status:tray.status,wearNotes:tray.wearNotes.trim()||null,visitId:tray.visitId?Number(tray.visitId):null};if(editingTray){await updateTray.mutateAsync({patientId:id,courseId:selected,trayId:editingTray,data})}else{await createTray.mutateAsync({patientId:id,courseId:selected,data:{...data,sequence:Number(tray.sequence)}})}refresh(selected);setEditingTray(0);setTray(emptyTray);setSaved(tr(ar,'Tray saved.','تم حفظ القالب.'))}catch(e){setError(errorText(e,ar))}}
 function beginEdit(t:AlignerTray){setEditingTray(t.id);setTray({sequence:String(t.sequence),plannedDate:t.plannedDate||'',deliveredDate:t.deliveredDate||'',status:t.status,wearNotes:t.wearNotes||'',visitId:String(t.visitId||'')});setError('');document.getElementById('tray-form')?.scrollIntoView({behavior:'smooth'})}
 return <main className="page care-hub"><BackLink href={`/patients/${id}`} label={tr(ar,'Patient profile','ملف المريض')}/><PageHeading eyebrow={tr(ar,'CLINICAL RECORD / ALIGNERS','السجل الطبي / القوالب الشفافة')} title={tr(ar,'Aligner courses','مسارات القوالب الشفافة')} subtitle={tr(ar,'A dated, visit-linked record of each tray in treatment.','سجل مؤرخ لكل قالب أثناء العلاج ومرتبط بالزيارات.')}/>{saved&&<div className="care-hub-note" role="status">{saved}</div>}{error&&<InlineError message={error}/>}
 <div className="care-hub-grid"><section className="care-hub-card"><h2>{tr(ar,'Courses','مسارات العلاج')}</h2>{courses.isLoading?<State kind="loading"/>:courses.isError?<State kind="error" onRetry={()=>courses.refetch()}/>:!courses.data?.length?<State kind="empty" title={tr(ar,'No aligner courses yet','لا توجد مسارات للقوالب بعد')} description={tr(ar,'Start a course from an orthodontic case.','ابدأ مسارًا من حالة تقويم موجودة.')}/>:<div className="care-hub-list">{courses.data.map(c=><button type="button" key={c.id} className="care-hub-item" style={{width:'100%',background:selected===c.id?'#edf5ef':'transparent',borderInline:0,borderBottom:0,textAlign:'start',cursor:'pointer',paddingInline:8,borderRadius:8}} onClick={()=>{setSelected(c.id);setEditingTray(0);setTray(emptyTray);setError('')}}><span><strong>{c.title}</strong><small>{tr(ar,'Orthodontic case','حالة تقويم')} #{c.caseId} · {c.trays.length} {tr(ar,'trays','قوالب')}</small></span></button>)}</div>}
 {writable&&<form className="care-hub-form" style={{marginTop:24}} onSubmit={saveCourse}><h2>{tr(ar,'Start a course','بدء مسار علاج')}</h2><label className="care-field">{tr(ar,'Course title','عنوان المسار')}<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="care-field">{tr(ar,'Orthodontic case','حالة التقويم')}<select required value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">{tr(ar,'Choose a case','اختر حالة')}</option>{cases.data?.map(c=><option key={c.id} value={c.id}>{c.title} · #{c.id}</option>)}</select></label>{cases.isError&&<State kind="error" onRetry={()=>cases.refetch()}/>}<button className="btn btn-primary" disabled={createCourse.isPending||cases.isLoading||!cases.data?.length}>{tr(ar,'Create course','إنشاء المسار')}</button></form>}</section>
 <section className="care-hub-card">{selected?<>{course.isLoading?<State kind="loading"/>:course.isError?<State kind="error" onRetry={()=>course.refetch()}/>:course.data?.patientId!==id?<State kind="denied"/>:course.data&&<><h2>{course.data.title}</h2><p>{tr(ar,'Orthodontic case','حالة التقويم')} #{course.data.caseId} · {tr(ar,'Started','بدأ')} {dateText(course.data.createdAt,ar)}</p>{!course.data.trays.length?<State kind="empty" title={tr(ar,'No trays recorded','لم تُسجل قوالب بعد')}/>:<div className="care-hub-list">{[...course.data.trays].sort((a,b)=>a.sequence-b.sequence).map(t=><div className="care-hub-item" key={t.id}><div><strong>{tr(ar,'Tray','القالب')} {t.sequence} <span className="care-pill">{careLabel(t.status,ar)}</span></strong><small>{tr(ar,'Planned','مخطط')}: {t.plannedDate?dateText(t.plannedDate,ar):'—'} · {tr(ar,'Delivered','سُلّم')}: {t.deliveredDate?dateText(t.deliveredDate,ar):'—'}</small>{t.wearNotes&&<p>{t.wearNotes}</p>}{t.visitId&&<small>{tr(ar,'Visit','زيارة')} #{t.visitId}</small>}</div>{writable&&<button className="btn btn-outline" onClick={()=>beginEdit(t)}>{tr(ar,'Update','تحديث')}</button>}</div>)}</div>}</>}</>:<State kind="empty" title={tr(ar,'Select a course','اختر مسارًا')} description={tr(ar,'Review tray progress and wear notes here.','راجع تقدم القوالب وملاحظات الارتداء هنا.')}/>}</section></div>
 {writable&&selected&&course.data?.patientId===id&&<section className="care-hub-card" id="tray-form"><h2>{editingTray?tr(ar,'Update tray','تحديث القالب'):tr(ar,'Add a tray','إضافة قالب')}</h2><form className="care-hub-form" onSubmit={saveTray}><label className="care-field">{tr(ar,'Sequence','الترتيب')}<input required min={1} type="number" value={tray.sequence} disabled={!!editingTray} onChange={e=>change('sequence',e.target.value)}/></label><label className="care-field">{tr(ar,'Planned date','التاريخ المخطط')}<input type="date" value={tray.plannedDate} onChange={e=>change('plannedDate',e.target.value)}/></label><label className="care-field">{tr(ar,'Delivered date','تاريخ التسليم')}<input type="date" value={tray.deliveredDate} onChange={e=>change('deliveredDate',e.target.value)}/></label><label className="care-field">{tr(ar,'Status','الحالة')}<select value={tray.status} onChange={e=>change('status',e.target.value as TrayStatus)}>{statuses.map(s=><option key={s} value={s}>{careLabel(s,ar)}</option>)}</select></label><label className="care-field">{tr(ar,'Linked visit','الزيارة المرتبطة')}<select value={tray.visitId} onChange={e=>change('visitId',e.target.value)}><option value="">{tr(ar,'No linked visit','دون زيارة مرتبطة')}</option>{visits.data?.map(v=><option value={v.id} key={v.id}>#{v.id} · {dateText(v.occurredAt,ar)}</option>)}</select></label>{visits.isError&&<State kind="error" onRetry={()=>visits.refetch()}/>}<label className="care-field">{tr(ar,'Wear notes','ملاحظات الارتداء')}<textarea maxLength={4000} value={tray.wearNotes} onChange={e=>change('wearNotes',e.target.value)}/></label>{error&&<InlineError message={error}/>}<div className="care-hub-actions"><button className="btn btn-primary" disabled={createTray.isPending||updateTray.isPending}>{tr(ar,'Save tray','حفظ القالب')}</button>{!!editingTray&&<button type="button" className="btn btn-outline" onClick={()=>{setEditingTray(0);setTray(emptyTray)}}>{tr(ar,'Cancel edit','إلغاء التعديل')}</button>}</div></form></section>}</main>;
}