import { useState, type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useParams } from 'wouter';
import { getListPatientPrescriptionsQueryKey, getGetPrescriptionQueryKey, getListPatientVisitsQueryKey, useListPatientPrescriptions, useGetPrescription, useCreatePatientPrescription, useAmendPrescription, useListPatientVisits, useListAppointmentDoctors, type StaffSession, type PrescriptionFields } from '@workspace/api-client-react';
import { BackLink, InlineError, PageHeading, State } from '@/components/clinic-ui';
import { useLocale } from '@/lib/locale';
import { cairoDay, careLabel as baseLabel, dateText, errorText, tr } from '@/lib/care';

const careLabel=(value:string,ar:boolean)=>ar?({issued:'صادرة',corrected:'مصححة',void:'مُبطلة',correction:'تصحيح'} as Record<string,string>)[value]||baseLabel(value,ar):baseLabel(value,ar);

const empty:PrescriptionFields={medication:'',dose:'',route:'',frequency:'',duration:'',instructions:''};
function MedicineFields({value,onChange,ar}:{value:PrescriptionFields;onChange:(value:PrescriptionFields)=>void;ar:boolean}){const fields:[keyof PrescriptionFields,string,string,number][]=[['medication','Medication','الدواء',200],['dose','Dose','الجرعة',120],['route','Route','طريقة التناول',80],['frequency','Frequency','التكرار',120],['duration','Duration','المدة',120],['instructions','Instructions','التعليمات',2000]];return <>{fields.map(([key,en,arabic,max])=><label className="care-field" key={key}>{tr(ar,en,arabic)}{key==='instructions'?<textarea maxLength={max} value={value[key]} onChange={e=>onChange({...value,[key]:e.target.value})}/>:<input required maxLength={max} value={value[key]} onChange={e=>onChange({...value,[key]:e.target.value})}/>}</label>)}</>}
export default function PatientPrescriptions({session}:{session:StaffSession}){
 const id=Number(useParams<{id:string}>().id),{language}=useLocale(),ar=language==='ar',qc=useQueryClient(),writable=['owner','dentist'].includes(session.role);
 const list=useListPatientPrescriptions(id,{query:{enabled:id>0,queryKey:getListPatientPrescriptionsQueryKey(id)}}),visits=useListPatientVisits(id,{query:{enabled:id>0&&writable,queryKey:getListPatientVisitsQueryKey(id)}}),doctors=useListAppointmentDoctors();
 const [selected,setSelected]=useState(0),detail=useGetPrescription(selected,{query:{enabled:selected>0,queryKey:getGetPrescriptionQueryKey(selected)}}),create=useCreatePatientPrescription(),amend=useAmendPrescription();
 const [med,setMed]=useState<PrescriptionFields>(empty),[issued,setIssued]=useState(()=>cairoDay(new Date())),[visit,setVisit]=useState(''),[dentist,setDentist]=useState(''),[mode,setMode]=useState<'correction'|'void'|''>(''),[replacement,setReplacement]=useState<PrescriptionFields>(empty),[reason,setReason]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const refresh=(prescriptionId:number)=>{void qc.invalidateQueries({queryKey:getListPatientPrescriptionsQueryKey(id)});void qc.invalidateQueries({queryKey:getGetPrescriptionQueryKey(prescriptionId)})};
 async function issue(e:FormEvent){e.preventDefault();setError('');setSaved('');try{const row=await create.mutateAsync({patientId:id,data:{...med,medication:med.medication.trim(),dose:med.dose.trim(),route:med.route.trim(),frequency:med.frequency.trim(),duration:med.duration.trim(),instructions:med.instructions.trim(),issuedDate:issued,...(visit?{visitId:Number(visit)}:{}),...(session.role==='owner'?{authorDentistStaffId:Number(dentist)}:{})}});refresh(row.id);setSelected(row.id);setMed(empty);setVisit('');setSaved(tr(ar,'Prescription issued.','تم إصدار الوصفة.'))}catch(e){setError(errorText(e,ar))}}
 async function saveAmendment(e:FormEvent){e.preventDefault();setError('');setSaved('');try{if(mode==='void')await amend.mutateAsync({prescriptionId:selected,data:{amendmentType:'void',reason:reason.trim()}});else await amend.mutateAsync({prescriptionId:selected,data:{amendmentType:'correction',reason:reason.trim(),replacement}});refresh(selected);setMode('');setReason('');setSaved(tr(ar,'Amendment recorded in the history.','تم تسجيل التعديل في السجل.'))}catch(e){setError(errorText(e,ar))}}
 return <main className="page care-hub"><BackLink href={`/patients/${id}`} label={tr(ar,'Patient profile','ملف المريض')}/><PageHeading eyebrow={tr(ar,'CLINICAL RECORD / PRESCRIPTIONS','السجل الطبي / الوصفات')} title={tr(ar,'Prescriptions','الوصفات الطبية')} subtitle={tr(ar,'Issue treatment instructions and preserve every correction.','أصدر تعليمات العلاج مع الحفاظ على سجل كل تصحيح.')}/>{saved&&<div className="care-hub-note" role="status">{saved}</div>}{error&&<InlineError message={error}/>}
 <div className="care-hub-grid"><section className="care-hub-card"><h2>{tr(ar,'Issued prescriptions','الوصفات الصادرة')}</h2>{list.isLoading?<State kind="loading"/>:list.isError?<State kind="error" onRetry={()=>list.refetch()}/>:!list.data?.length?<State kind="empty" title={tr(ar,'No prescriptions yet','لا توجد وصفات بعد')} description={tr(ar,'Issued prescriptions appear here with their amendment history.','ستظهر الوصفات الصادرة هنا مع سجل تعديلاتها.')}/>:<div className="care-hub-list">{list.data.map(p=><button type="button" className="care-hub-item" key={p.id} style={{width:'100%',background:selected===p.id?'#edf5ef':'transparent',borderInline:0,borderBottom:0,textAlign:'start',cursor:'pointer',paddingInline:8,borderRadius:8}} onClick={()=>{setSelected(p.id);setMode('');setError('')}}><span><strong>{p.medication} · {p.dose}</strong><small>#{p.id} · {dateText(p.issuedDate,ar)} · {p.authorDentistName}</small></span><span className="care-pill">{careLabel(p.status,ar)}</span></button>)}</div>}</section>
 <section className="care-hub-card">{selected?<>{detail.isLoading?<State kind="loading"/>:detail.isError?<State kind="error" onRetry={()=>detail.refetch()}/>:detail.data?.patientId!==id?<State kind="denied"/>:detail.data&&<><h2>{detail.data.medication} <span className="care-pill">{careLabel(detail.data.status,ar)}</span></h2><div className="care-hub-note">{detail.data.dose} · {detail.data.route} · {detail.data.frequency} · {detail.data.duration}</div>{detail.data.instructions&&<p>{detail.data.instructions}</p>}<small className="care-hub-meta">{tr(ar,'Issued','صادرة')}: {dateText(detail.data.issuedDate,ar)} · {detail.data.authorDentistName}{detail.data.visitId?` · ${tr(ar,'Visit','زيارة')} #${detail.data.visitId}`:''}</small>{writable&&detail.data.status!=='void'&&<div className="care-hub-actions" style={{marginTop:18}}><button className="btn btn-outline" onClick={()=>{setMode('correction');setReplacement({medication:detail.data!.medication,dose:detail.data!.dose,route:detail.data!.route,frequency:detail.data!.frequency,duration:detail.data!.duration,instructions:detail.data!.instructions});setReason('')}}>{tr(ar,'Correct','تصحيح')}</button><button className="btn btn-outline" onClick={()=>{setMode('void');setReason('')}}>{tr(ar,'Void prescription','إبطال الوصفة')}</button></div>}
 <h2 style={{marginTop:28}}>{tr(ar,'Amendment history','سجل التعديلات')}</h2><div className="care-hub-list"><div className="care-hub-item"><div><strong>{tr(ar,'Original issue','الإصدار الأصلي')}</strong><small>{detail.data.original.medication} · {detail.data.original.dose} · {detail.data.original.route} · {detail.data.original.frequency} · {detail.data.original.duration}</small>{detail.data.original.instructions&&<small>{detail.data.original.instructions}</small>}</div></div>{detail.data.amendments.map(a=><div className="care-hub-item" key={a.id}><div><strong>{careLabel(a.amendmentType,ar)} · {a.amendedByName}</strong><small>{dateText(a.createdAt,ar,{hour:'2-digit',minute:'2-digit'})}</small><p>{a.reason}</p>{a.replacement&&<small>{a.replacement.medication} · {a.replacement.dose} · {a.replacement.route} · {a.replacement.frequency} · {a.replacement.duration} · {a.replacement.instructions}</small>}</div></div>)}</div></>}</>:<State kind="empty" title={tr(ar,'Select a prescription','اختر وصفة')} description={tr(ar,'Review the current instructions and their amendment trail.','راجع التعليمات الحالية وسجل تعديلاتها.')}/>}</section></div>
 {writable&&<section className="care-hub-card"><h2>{tr(ar,'Issue a prescription','إصدار وصفة')}</h2><form className="care-hub-form" onSubmit={issue}><MedicineFields ar={ar} value={med} onChange={setMed}/><label className="care-field">{tr(ar,'Issue date','تاريخ الإصدار')}<input required type="date" value={issued} onChange={e=>setIssued(e.target.value)}/></label><label className="care-field">{tr(ar,'Visit (optional)','الزيارة (اختياري)')}<select value={visit} onChange={e=>setVisit(e.target.value)}><option value="">{tr(ar,'No linked visit','دون زيارة مرتبطة')}</option>{visits.data?.map(v=><option value={v.id} key={v.id}>#{v.id} · {dateText(v.occurredAt,ar)}</option>)}</select></label>{visits.isError&&<State kind="error" onRetry={()=>visits.refetch()}/>} {session.role==='owner'&&<label className="care-field">{tr(ar,'Authoring dentist','الطبيب المُصدر')}<select required value={dentist} onChange={e=>setDentist(e.target.value)}><option value="">{tr(ar,'Choose a dentist','اختر طبيبًا')}</option>{doctors.data?.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}{doctors.isError&&session.role==='owner'&&<State kind="error" onRetry={()=>doctors.refetch()}/>}<button className="btn btn-primary" disabled={create.isPending}>{tr(ar,'Issue prescription','إصدار الوصفة')}</button></form></section>}
 {writable&&mode&&detail.data?.patientId===id&&<div className="care-dialog"><form className="care-panel care-hub-form" style={{padding:24,width:'min(100%,520px)',maxHeight:'90dvh',overflowY:'auto'}} onSubmit={saveAmendment}><h2>{mode==='void'?tr(ar,'Void prescription','إبطال الوصفة'):tr(ar,'Record a correction','تسجيل تصحيح')}</h2><p className="subtle">{tr(ar,'The original prescription remains in the audit history.','تبقى الوصفة الأصلية محفوظة في سجل التعديلات.')}</p><label className="care-field">{tr(ar,'Reason for amendment','سبب التعديل')}<textarea required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{mode==='correction'&&<MedicineFields ar={ar} value={replacement} onChange={setReplacement}/>} {error&&<InlineError message={error}/>}<div className="care-hub-actions"><button className="btn btn-primary" disabled={amend.isPending}>{tr(ar,'Record amendment','تسجيل التعديل')}</button><button type="button" className="btn btn-outline" onClick={()=>{setMode('');setError('')}}>{tr(ar,'Cancel','إلغاء')}</button></div></form></div>}</main>;
}