import { useEffect, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useParams } from 'wouter';
import { getGetPatientReminderPreferencesQueryKey, useGetPatientReminderPreferences, useSetPatientReminderPreferences, type ReminderPreferencesInputChannel, type StaffSession } from '@workspace/api-client-react';
import { BackLink, InlineError, PageHeading, State } from '@/components/clinic-ui';
import { useLocale } from '@/lib/locale';
import { dateText, errorText, tr } from '@/lib/care';

export default function PatientReminderPreferences({session:_session}:{session:StaffSession}){
 const id=Number(useParams<{id:string}>().id),{language}=useLocale(),ar=language==='ar',qc=useQueryClient();
 const q=useGetPatientReminderPreferences(id,{query:{enabled:id>0,queryKey:getGetPatientReminderPreferencesQueryKey(id),retry:false}}),save=useSetPatientReminderPreferences();
  const [optIn,setOptIn]=useState(false),[channel,setChannel]=useState<ReminderPreferencesInputChannel>('whatsapp'),[error,setError]=useState(''),[success,setSuccess]=useState('');
  useEffect(()=>{setOptIn(q.data?.optIn??false);setChannel(q.data?.channel??'whatsapp')},[id,q.data]);
  useEffect(()=>{setError('');setSuccess('')},[id]);
 const missing=q.isError&&((q.error as {status?:number;response?:{status?:number}}).status===404||(q.error as {response?:{status?:number}}).response?.status===404);
  async function submit(e:React.FormEvent){e.preventDefault();setError('');setSuccess('');try{const data=await save.mutateAsync({patientId:id,data:{optIn,channel}});qc.setQueryData(getGetPatientReminderPreferencesQueryKey(id),data);setSuccess(tr(ar,'Preferences saved. Consent is recorded by the clinic, not by a messaging provider.','تم حفظ التفضيلات. تسجّل العيادة الموافقة، وليس مزوّد الرسائل.'))}catch(e){setError(errorText(e,ar))}}
 return <main className="page care-hub"><BackLink href={`/patients/${id}`} label={tr(ar,'Patient profile','ملف المريض')}/><PageHeading eyebrow={tr(ar,'PATIENT COMMUNICATION','التواصل مع المريض')} title={tr(ar,'Reminder preferences','تفضيلات التذكير')} subtitle={tr(ar,'Contact only when the patient has opted in.','تواصل فقط بعد موافقة المريض.')}/>{q.isLoading?<State kind="loading"/>:q.isError&&!missing?<State kind="error" onRetry={()=>q.refetch()}/>:<div className="care-hub-grid"><section className="care-hub-card"><h2>{tr(ar,'Recorded preference','التفضيل المسجل')}</h2>{missing?<p>{tr(ar,'No preference has been recorded for this patient.','لم تُسجَّل تفضيلات لهذا المريض بعد.')}</p>:<><div className={`badge ${q.data?.optIn?'':'muted'}`}>{q.data?.optIn?tr(ar,'Opted in','موافق'):tr(ar,'Opted out','غير موافق')}</div><p>{tr(ar,'Preferred channel','قناة التواصل')}: {q.data?.channel}</p><p className="care-hub-meta">{q.data?.consentRecordedAt&&`${tr(ar,'Consent recorded','تسجيل الموافقة')}: ${dateText(q.data.consentRecordedAt,ar)}`}</p></>}</section><section className="care-hub-card"><h2>{tr(ar,'Update with patient authorization','تحديث بتفويض المريض')}</h2><form className="care-hub-form" onSubmit={submit}><label className="care-hub-note"><input type="checkbox" checked={optIn} onChange={e=>setOptIn(e.target.checked)}/> {tr(ar,'The patient explicitly agrees to appointment reminders.','يوافق المريض صراحةً على تذكيرات المواعيد.')}</label><label className="care-field">{tr(ar,'Preferred channel','قناة التواصل المفضلة')}<select value={channel} onChange={e=>setChannel(e.target.value as ReminderPreferencesInputChannel)}><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="email">{tr(ar,'Email','البريد الإلكتروني')}</option></select></label><p className="care-hub-meta">{tr(ar,'Saving opt-in records the current consent time. Untick to revoke.','حفظ الموافقة يسجل وقتها الحالي. أزل العلامة لسحبها.')}</p><button className="btn btn-primary" disabled={save.isPending}>{tr(ar,'Save preferences','حفظ التفضيلات')}</button>{error&&<InlineError message={error}/>} {success&&<p className="care-hub-note" role="status">{success}</p>}</form></section></div>}</main>
}