import { useState, type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'wouter';
import { getListPatientLaboratoryOrdersQueryKey, getGetLaboratoryOrderQueryKey, getListPatientVisitsQueryKey, getListSuppliersQueryKey, useListPatientLaboratoryOrders, useGetLaboratoryOrder, useCreatePatientLaboratoryOrder, useUpdateLaboratoryOrder, useCancelLaboratoryOrder, useListPatientVisits, useListSuppliers, type StaffSession, type LaboratoryOrder, type LaboratoryCaseType, type LaboratoryOrderStatus } from '@workspace/api-client-react';
import { BackLink, InlineError, PageHeading, State } from '@/components/clinic-ui';
import { useLocale } from '@/lib/locale';
import { careLabel as baseLabel, dateText, errorText, tr } from '@/lib/care';

const careLabel=(value:string,ar:boolean)=>ar?({submitted:'مُرسل',ready:'جاهز',delivered:'تم التسليم',bridge:'جسر',denture:'طقم أسنان',orthodontic:'تقويم',create:'إنشاء',update:'تحديث',cancel:'إلغاء'} as Record<string,string>)[value]||baseLabel(value,ar):baseLabel(value,ar);

type Form = {labName:string; supplierId:string; visitId:string; caseType:LaboratoryCaseType; dueDate:string; notes:string; status:LaboratoryOrderStatus};
const blank:Form={labName:'',supplierId:'',visitId:'',caseType:'crown',dueDate:'',notes:'',status:'submitted'};
const types:LaboratoryCaseType[]=['crown','bridge','denture','implant','orthodontic','other'];
const nextStatus:Record<string,LaboratoryOrderStatus[]>={submitted:['submitted','in_progress'],in_progress:['in_progress','ready'],ready:['ready','in_progress','delivered']};
const field=(o:LaboratoryOrder):Form=>({labName:o.labName,supplierId:String(o.supplierId||''),visitId:String(o.visitId||''),caseType:o.caseType,dueDate:o.dueDate?.slice(0,10)||'',notes:o.notes||'',status:o.status});

export default function PatientLaboratory({session}:{session:StaffSession}){
 const id=Number(useParams<{id:string}>().id),{language}=useLocale(),ar=language==='ar',qc=useQueryClient(),canWrite=['owner','dentist'].includes(session.role);
  const list=useListPatientLaboratoryOrders(id,{query:{enabled:id>0,queryKey:getListPatientLaboratoryOrdersQueryKey(id)}}),visits=useListPatientVisits(id,{query:{enabled:id>0&&canWrite,queryKey:getListPatientVisitsQueryKey(id)}}),suppliers=useListSuppliers({query:{enabled:session.role==='owner',queryKey:getListSuppliersQueryKey()}});
 const [selected,setSelected]=useState(0),detail=useGetLaboratoryOrder(selected,{query:{enabled:selected>0,queryKey:getGetLaboratoryOrderQueryKey(selected)}}),create=useCreatePatientLaboratoryOrder(),update=useUpdateLaboratoryOrder(),cancel=useCancelLaboratoryOrder();
 const [form,setForm]=useState<Form>(blank),[editing,setEditing]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const refresh=(orderId:number)=>{void qc.invalidateQueries({queryKey:getListPatientLaboratoryOrdersQueryKey(id)});void qc.invalidateQueries({queryKey:getGetLaboratoryOrderQueryKey(orderId)})};
 const change=<K extends keyof Form>(key:K,value:Form[K])=>setForm(f=>({...f,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setError('');setSaved('');try{
  const data={labName:form.labName.trim(),supplierId:form.supplierId?Number(form.supplierId):null,visitId:form.visitId?Number(form.visitId):null,caseType:form.caseType,dueDate:form.dueDate||null,notes:form.notes.trim()||null};
  if(editing){await update.mutateAsync({orderId:selected,data:{...data,status:form.status}});refresh(selected)}else{const row=await create.mutateAsync({patientId:id,data});refresh(row.id);setSelected(row.id)}
  setEditing(false);setForm(blank);setSaved(tr(ar,'Order saved.','تم حفظ الطلب.'));
 }catch(e){setError(errorText(e,ar))}}
 async function cancelOrder(){if(!detail.data||!window.confirm(tr(ar,'Cancel this laboratory order? Its history will remain available.','هل تريد إلغاء طلب المعمل؟ سيظل سجله متاحًا.')))return;setError('');setSaved('');try{await cancel.mutateAsync({orderId:selected});refresh(selected);setSaved(tr(ar,'Order cancelled.','تم إلغاء الطلب.'))}catch(e){setError(errorText(e,ar))}}
 return <main className="page care-hub"><BackLink href={`/patients/${id}`} label={tr(ar,'Patient profile','ملف المريض')}/><PageHeading eyebrow={tr(ar,'CLINICAL RECORD / LABORATORY','السجل الطبي / المعمل')} title={tr(ar,'Laboratory orders','طلبات المعمل')} subtitle={tr(ar,'Track cases from submission through delivery, with a reliable change history.','تابع الحالات من الطلب حتى التسليم مع سجل موثوق للتغييرات.')} action={canWrite?<button className="btn btn-primary" onClick={()=>{setEditing(false);setForm(blank);setError('');setSelected(0);document.getElementById('lab-form')?.scrollIntoView({behavior:'smooth'})}}>{tr(ar,'New order','طلب جديد')}</button>:undefined}/>
 {saved&&<div className="care-hub-note" role="status">{saved}</div>}{error&&<InlineError message={error}/>}
 <div className="care-hub-grid"><section className="care-hub-card"><h2>{tr(ar,'Orders','الطلبات')}</h2>{list.isLoading?<State kind="loading"/>:list.isError?<State kind="error" onRetry={()=>list.refetch()}/>:!list.data?.length?<State kind="empty" title={tr(ar,'No laboratory orders yet','لا توجد طلبات معمل بعد')} description={tr(ar,'New orders will appear here with their current status.','ستظهر الطلبات الجديدة هنا مع حالتها الحالية.')}/>:<div className="care-hub-list">{list.data.map(o=><button type="button" key={o.id} className="care-hub-item" style={{width:'100%',background:selected===o.id?'#edf5ef':'transparent',borderInline:0,borderBottom:0,textAlign:'start',cursor:'pointer',paddingInline:8,borderRadius:8}} onClick={()=>{setSelected(o.id);setEditing(false);setSaved('');setError('')}}><span><strong>{o.labName} · {careLabel(o.caseType,ar)}</strong><small>#{o.id} · {o.dueDate?dateText(o.dueDate,ar):tr(ar,'No due date','دون موعد تسليم')}</small></span><span className="care-pill">{careLabel(o.status,ar)}</span></button>)}</div>}</section>
 <section className="care-hub-card">{selected?<>{detail.isLoading?<State kind="loading"/>:detail.isError?<State kind="error" onRetry={()=>detail.refetch()}/>:detail.data?.patientId!==id?<State kind="denied"/>:detail.data&&<><h2>{detail.data.labName} <span className="care-pill">{careLabel(detail.data.status,ar)}</span></h2><div className="care-hub-note">{tr(ar,'Case','الحالة')}: {careLabel(detail.data.caseType,ar)} · {tr(ar,'Due','الاستحقاق')}: {detail.data.dueDate?dateText(detail.data.dueDate,ar):'—'}<br/>{tr(ar,'Supplier','المورد')}: {suppliers.data?.find(s=>s.id===detail.data?.supplierId)?.name||'—'} · {tr(ar,'Visit','الزيارة')}: {detail.data.visitId?<Link href={`/visits/${detail.data.visitId}`}>#{detail.data.visitId}</Link>:'—'}</div>{detail.data.notes&&<p>{detail.data.notes}</p>}<small className="care-hub-meta">{tr(ar,'Created','أُنشئ')}: {dateText(detail.data.createdAt,ar)} · {tr(ar,'Updated','حُدّث')}: {dateText(detail.data.updatedAt,ar)}</small>{canWrite&&detail.data.status!=='cancelled'&&detail.data.status!=='delivered'&&<div className="care-hub-actions" style={{marginTop:18}}><button className="btn btn-outline" onClick={()=>{setForm(field(detail.data!));setEditing(true);setError('');document.getElementById('lab-form')?.scrollIntoView({behavior:'smooth'})}}>{tr(ar,'Edit order','تعديل الطلب')}</button><button className="btn btn-outline" disabled={cancel.isPending} onClick={cancelOrder}>{tr(ar,'Cancel order','إلغاء الطلب')}</button></div>}<h2 style={{marginTop:28}}>{tr(ar,'Change history','سجل التغييرات')}</h2>{!detail.data.history.length?<State kind="empty" title={tr(ar,'No changes recorded','لم تُسجل تغييرات')}/>:<div className="care-hub-list">{detail.data.history.map(h=><div key={h.id} className="care-hub-item"><div><strong>{careLabel(h.action,ar)} · {h.actorName}</strong><small>{dateText(h.occurredAt,ar,{hour:'2-digit',minute:'2-digit'})}</small>{h.action==='update'&&<small>{tr(ar,'Order details updated','تم تحديث بيانات الطلب')}</small>}</div></div>)}</div>}</>}</>:<State kind="empty" title={tr(ar,'Select an order','اختر طلبًا')} description={tr(ar,'Open an order to review its details and history.','افتح طلبًا لمراجعة تفاصيله وسجله.')}/>}</section></div>
 {canWrite&&(!selected||editing)&&<section className="care-hub-card" id="lab-form"><h2>{editing?tr(ar,'Edit laboratory order','تعديل طلب المعمل'):tr(ar,'New laboratory order','طلب معمل جديد')}</h2><form className="care-hub-form" onSubmit={submit}><label className="care-field">{tr(ar,'Laboratory name','اسم المعمل')}<input required maxLength={200} value={form.labName} onChange={e=>change('labName',e.target.value)}/></label><label className="care-field">{tr(ar,'Supplier (optional)','المورد (اختياري)')}<select value={form.supplierId} onChange={e=>change('supplierId',e.target.value)}><option value="">{tr(ar,'No supplier','دون مورد')}</option>{suppliers.data?.filter(s=>s.active||String(s.id)===form.supplierId).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>{suppliers.isError&&<State kind="error" onRetry={()=>suppliers.refetch()}/>}<label className="care-field">{tr(ar,'Linked visit (optional)','الزيارة المرتبطة (اختياري)')}<select value={form.visitId} onChange={e=>change('visitId',e.target.value)}><option value="">{tr(ar,'No visit','دون زيارة')}</option>{visits.data?.map(v=><option value={v.id} key={v.id}>#{v.id} · {dateText(v.occurredAt,ar)}</option>)}</select></label>{visits.isError&&<State kind="error" onRetry={()=>visits.refetch()}/>}<label className="care-field">{tr(ar,'Case type','نوع الحالة')}<select value={form.caseType} onChange={e=>change('caseType',e.target.value as LaboratoryCaseType)}>{types.map(t=><option value={t} key={t}>{careLabel(t,ar)}</option>)}</select></label><label className="care-field">{tr(ar,'Due date','موعد التسليم')}<input type="date" value={form.dueDate} onChange={e=>change('dueDate',e.target.value)}/></label>{editing&&<label className="care-field">{tr(ar,'Status','الحالة')}<select value={form.status} onChange={e=>change('status',e.target.value as LaboratoryOrderStatus)}>{(nextStatus[detail.data?.status||'submitted']||[]).map(s=><option value={s} key={s}>{careLabel(s,ar)}</option>)}</select></label>}<label className="care-field">{tr(ar,'Notes','ملاحظات')}<textarea maxLength={10000} value={form.notes} onChange={e=>change('notes',e.target.value)}/></label>{error&&<InlineError message={error}/>}<div className="care-hub-actions"><button className="btn btn-primary" disabled={create.isPending||update.isPending}>{tr(ar,'Save order','حفظ الطلب')}</button>{editing&&<button type="button" className="btn btn-outline" onClick={()=>{setEditing(false);setError('')}}>{tr(ar,'Discard changes','تجاهل التغييرات')}</button>}</div></form></section>}</main>;
}